Repository openshift-knative/knative-serving-operator, pull requests merged in 2019-11, with the labels that each got.

#72 add changes to auto install ServiceMeshControlPlane and ServiceMeshMemberRole
  Gopkg.lock
  Gopkg.toml
  deploy/resources/serviceMesh/smcp.yaml
  pkg/apis/addtoschema_gateway_v1alpha3.go
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
  pkg/controller/knativeserving/common/extensions.go
  pkg/controller/knativeserving/knativeserving_controller.go
  pkg/controller/knativeserving/minikube/minikube.go
  pkg/controller/knativeserving/openshift/openshift.go
  vendor/knative.dev/pkg/LICENSE
  vendor/knative.dev/pkg/apis/istio/common/v1alpha1/string.go
  vendor/knative.dev/pkg/apis/istio/register.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/destinationrule_types.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/doc.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/gateway_types.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/register.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/third_party/mako/LICENSE
Labels: lgtm, size/XXL

#74 Make error messages more user friendly.
  pkg/controller/knativeserving/knativeserving_controller.go
  pkg/controller/knativeserving/openshift/openshift.go
Labels: size/XS

#75 Add owner reference to namespace where service mesh install
  pkg/controller/knativeserving/openshift/openshift.go
Labels: lgtm, size/S

#76 Replace cross-ns owner refs with finalizer.
  pkg/controller/knativeserving/common/extensions.go
  pkg/controller/knativeserving/knativeserving_controller.go
  pkg/controller/knativeserving/openshift/openshift.go
Labels: size/M

#77 Fetch KnativeServing again before updating to remove the finalizer.
  pkg/controller/knativeserving/knativeserving_controller.go
Labels: size/S

#79 handle separately MutatingWebhookConfiguration and ValidatingWebhookConfiguration and add changes for knative 0.10.0 release
  deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/knative-serving-0.10.0.yaml
  deploy/resources/webhook/webhook.yaml
  pkg/controller/knativeserving/knativeserving_controller.go
  version/version.go
Labels: size/XXL
