Repository openshift-knative/knative-serving-operator, pull requests merged in 2019-10, with the labels that each got.

#67 Backport SRVKS-270
  deploy/resources/knative-serving-0.8.1.yaml
Labels: size/S

#66 expose health status of knative serving operator to prometheus
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
  pkg/controller/knativeserving/knativeserving_controller.go
Labels: size/M

#68 Use 0.8.1 version for edit and view roles
  deploy/resources/knative-serving-0.8.1.yaml
Labels: lgtm, size/XS

#69 fix missing events while exposing operator health status
  pkg/controller/knativeserving/knativeserving_controller.go
Labels: size/XS

#73 [SRVKS-281] Explicit RBAC resources for non-cluster admins
  deploy/resources/knative-serving-0.9.0.yaml
Labels: lgtm, size/S
